### ISSUE TITLE
cannot open enrollments outside assigned data capture OU unless: data output OU set to root or superuser

### ISSUE THREAD

**Issue by iambodo** [HRHR-project/e-registry-app#104]
MAJOR ISSUE

Non-superusers cannot access enrollments created by other users.

Test 1 description
Replicated a model field user. 
mFWA_int_csba P eReg!234
mFWA_int1_csba: https://bd-eregistry.dhis2.org/dhis/api/users/WKmpWU0TeMR

Initially changed the data capture org unit to another OU within the same unit (Unit 1/Ka)

With the original user, created a new TEI and client enrollment, "ironman"
https://bd-eregistry.dhis2.org/dhis/api/apps/E-Registry/index.html#/dashboard?tei=WpXFMKRfNs9&program=ZBIqxwVixn8&ou=gpvBLKLRt8j

With the replicant user, was unable to see the original enrollment
![image](https://user-images.githubusercontent.com/36451485/41473521-d5d7b182-70b9-11e8-9613-eb80e243970e.png)

When I try to add a new enrollment with replicant user, client console reads: angular.js:9866 PUT https://bd-eregistry.dhis2.org/dhis/api/29/trackedEntityInstances/WpXFMKRfNs9 409 (Conflict) 

BEcause there is an existing enrollment.

Test 2
I then added more user groups and roles to the replicant user (short of superuser).  Same result when searching for the original user. 

Test 3
I also gave the replicant user write access to the registration org unit. Now, I am able to view the enrollment with the new replicant user.

Test 4
Note: can access the enrollment as a super-user just fine, from any org unit
![image](https://user-images.githubusercontent.com/36451485/41473185-d4dc3cf4-70b8-11e8-8455-e7fd3e95c13a.png)

**Comment by Bekkalizer** [comment]
*putting on black sabbath*

**Comment by RahmanMonjur** [comment]
Have you tried with intfac user?

**Comment by iambodo** [comment]
Thanks  @RahmanMonjur for looking into it, this also worked for me.
seems like the problem is with 

**Data output and analytic organisation units**

intfac was set to all of Matlab North, meaning it could access enrollments from the entire uppazilla.

When I uncheck the data output OU, it resets to root. This seems to solve the problem of user access.
![image](https://user-images.githubusercontent.com/36451485/41556124-1b22fdc8-733a-11e8-9e97-267f7ee124c4.png)


However, I am not closing this issue. For the dashboards, we **need** to set data output OU to the user's data capture OU. Otherwise we would have to create separate dashboards for each clinic.
https://docs.dhis2.org/2.26/en/user/html/mgt_user.html

It seems that when the eRegistry app checks user permissions to access enrollments (or an enrollment's program indicators), it may be checking the against an aggregated data table.

changing the name.

**Comment by Wonfrost** [comment]
@Bekkalizer , I just double checked this problem. It does seem like the data capture org unit for the user is interfering with the search org unit. With search set at the highest level (Bangladesh), they can find the tracked entity, but it doesn't show that it has an enrollment. Then if you try to enroll the TEI, there is an error saying that this TEI already has an enrollment.

**Comment by AkubaD** [comment]
Hi @RahmanMonjur 
there will need to be a WAR file update to fix this. Could you let us know when it can be done?

**Comment by RahmanMonjur** [comment]
@AkubaD WAR or app? I'm not seeing any update/change message.

**Comment by AkubaD** [comment]
@RahmanMonjur 
@iambodo had said WAR, but I guess it might be app if you are not seeing change message

**Comment by Bekkalizer** [comment]
The limit of what the user can see is now the "Search" org unit:
https://github.com/dhis2/dhis2-core/commit/54ecedea2465a82b956d75ae477f115957888809
@RahmanMonjur 
Build and deploy a new WAR file based on the 2.29 palestine branch(above) - this will resolve your issue.

**Comment by RahmanMonjur** [comment]
@Bekkalizer I'm getting en error while running mvn install command.[
<img width="845" alt="screen shot 2018-07-24 at 22 07 35" src="https://user-images.githubusercontent.com/6468891/43151602-274c0426-8f8e-11e8-9928-9734a784d2ac.png">
](url)

**Comment by lukasewvd** [comment]
Has the been resolved with the update @Bekkalizer provided?

**Comment by AkubaD** [comment]
Hi @Bekkalizer @lukasewvd 
@RahmanMonjur and I tried the new WAR file. It did not solve the issue.
 @iambodo just double checked and apparently the update does not work in Palestine after all: If a user's data output org unit is not set above or (equal to) the org unit of an existing TEI, the user cannot access the TEI's enrollment.
So the fix did not work.
Markus could you take a look?

**Comment by lukasewvd** [comment]
Hi @AkubaD, did you also assign "search orgunits"?  As @Bekkalizer says in the comment above: _"The limit of what the user can see is now the "Search" org unit"_.

**Comment by AkubaD** [comment]
Hi @lukasewvd 
Yes. Search org units is set to the entire Bangladesh.

**Comment by iambodo** [comment]
Hi all, this issue is still showing in both the hrhr and bd dev systems.

Test 1 Palestine
With this user my search org unit is set to Palestine and my data capture and maintenance org units are set to Al Zawida.
https://hrhr.dhis2.org/dhis/dhis-web-maintenance-user/showUpdateUserForm.action?id=1005327

But when I try to open an enrollment that was made outside Al Zawida, I get placeholders for the dropdown menu options (note the "_"), and I also cannot open the selected enrollment. See this video:
https://www.useloom.com/share/0e91d6834b444da781b76b62ff17ad29

But there *is* an active enrollment for this TEI: 
![image](https://user-images.githubusercontent.com/36451485/43704766-057003d4-9961-11e8-8bca-e4651b16cbe3.png)

Test2 Bangladesh
This TEI is registered at Rayerkandi FWC. I can access the record as a superuser (data output at all org units) while entering data at Khaguirya CC. 
https://bd-eregistry.dhis2.org/dhis/api/apps/E-Registry/index.html#/dashboard?tei=T2XCiVJ1F8M&program=WSGAb5XwJ3Y&ou=Law6euHPccf
![image](https://user-images.githubusercontent.com/36451485/43705132-03be1d9a-9962-11e8-8455-0adb699bfc59.png)

BUT, when i enter these data as a superuser who ONLY has access to Khaguriya CC (user: dash_test_khag), I cannot open the enrollment. I try to enroll this TEI again, and I get a 409 conflict.
https://www.useloom.com/share/6f3ab0e6d903471d8cf5713d5ca0a263
