### ISSUE TITLE
Bug in stage read access permissions

### ISSUE THREAD

**Issue by AkubaD** [HRHR-project/e-registry-app#55]
Our design requires some stages to be read only for some of our users.
I have set the user permissions for this stage to be as below: 
View only for metadata
View only for data capture.
This user should not be able to create a new instance of the stage. But that stage shows up in the list of options when you try to create a stage. But when you click Save to create an instance of that stage, it hangs and does nothing - probably because that user should not be able to create that stage.
Bug: the stage should not show up in the drop down of available stages to be created when you create the + stage create button

![image](https://user-images.githubusercontent.com/36447512/37900817-9f1f90b0-30ef-11e8-8990-4478dd0fea6c.png)

**Comment by AkubaD** [comment]
Hi @lukasewvd  and @Bekkalizer 
Could I get an update on this
This user has read access to this stage. But when you click on the plus button to create a new stage, this Read only stage shows up in the list of stage options, but when you click to Save, it does nothing and the pop up stays until you click Cancel. 

![image](https://user-images.githubusercontent.com/36447512/38820739-fc4d1a86-419e-11e8-831d-7f634feea1f3.png)

**Comment by AkubaD** [comment]
Hi @Bekkalizer 
We have made further read only restrictions for some of our stages, so this bug is becoming a real issue for us.
To replicate:
Log in as mCHCP_int1  password eReg!234
Create a user in the Client Register program (you can enter just the required attributes, Name, Age and Village name). 
Try to create an instance of the TT History stage - it will allow you to proceed and generate an event date. But when you click Save to create the event, nothing happens -because you have read only permissions for the stage. It generates a 409 Conflict related to the event. See screenshot below
Same with the TT Service Delivery stage. 

The issue: the plus sign for adding an event should not exist for users who do not have data capture permissions for that stage,. 

A user that has data capture access to the TT History stage is intfwaEng password eReg!234
For this user, you are able to proceed and save the date to create the event and enter data, as it should be.
But this user has only read access to the TT Service Delivery stage, and you get this issue of 409 conflict when that user tries to create a TT Service Delivery event

![image](https://user-images.githubusercontent.com/36447512/42819568-42b2acfc-89d4-11e8-8cfa-61dcd89d1f9b.png)

**Comment by lukasewvd** [comment]
This should now be fixed.

**Comment by AkubaD** [comment]
Hi @RahmanMonjur 
Has this been deployed yet because I'm still experiencing this issue.

**Comment by AkubaD** [comment]
Hi @lukasewvd 
@RahmanMonjur did the deploy for this today.
It does not work at all only in the MCH program - it does not allow creation of ANY program stage in the MCH program, even for *admin* users. 
It seems to work okay in the Client register program - it gives the message to the appropriate users who do not have write access to the appropriate stages. There is a display issue for one of the stages, but I think it can be fixed when we deploy the solution to issue #106 

I am not getting any errors or warnings in the console that would be related
To replicate, you can log in as intfwaEng eReg!234
In Client register, that user has write access to one stage (TT History) and read access to another (TT-Service). That works fine.
In MCH program, it has write access to all the stages displayed. 

![image](https://user-images.githubusercontent.com/36447512/44207029-fd62b300-a15b-11e8-9663-f578efabc070.png)

**Comment by lukasewvd** [comment]
I have pushed a possible fix (c659d36a301e8b99b814fe9c7b7b751d500a9fa6) which addresses this issue.

**Comment by AkubaD** [comment]
Hi @lukasewvd 
Is this fix different from what you skyped me about on Friday? Monjur already deployed that and I'm testing it now. Is there an updated fix that you want us to deploy and test?

**Comment by AkubaD** [comment]
Hi @lukasewvd 
This seems to be working - it allows and does not allow creation of events correctly. But we get at least 3 different error messages and we need some consistency. I think the best way to test this is to have the solution to #106 incorporated as well and see the behavior when both programs have the UI of the MCH program. @RahmanMonjur mentioned that it is still in the pull-request box. It has not been merged yet to the main code. Could this be done?

**Comment by AkubaD** [comment]
This is a problem: It shows a blank program stage drop down list for a user who only has read access to all the program stages in this program
![image](https://user-images.githubusercontent.com/36447512/44339464-c6551000-a481-11e8-9e37-47bf2a6cbbd9.png)

**Comment by AkubaD** [comment]
Here are the error messages - not errors in the console, but the pop-up error messages to the user.
This is in the Client register for a user who only has read access to all the program stages in that program. I think we prefer the previous error message saying that you do not have write access to the program stages.
![image](https://user-images.githubusercontent.com/36447512/44339530-fc928f80-a481-11e8-92ed-78f7892b18a0.png)

This error message you get in MCH program when trying to add a stage that you only have read access to. It is the one we would prefer – it gives the most accurate message – that New visit cannot be created. Best to say ‘New visit/event can not be created’. However the additional message is incorrect. You *have* data write access to other program stages, but not to this one. In MCH program, the UI is such that you create program stages within the menu ‘box’ of that program stage. So you may not be able to create a new event of your selected program stage, but you can still have other program stages that you have write access to. So message should say:
‘New Visit/event cannot be created. ‘You do not have data write access to this program stage.’

![image](https://user-images.githubusercontent.com/36447512/44339600-40859480-a482-11e8-9709-3da6e14a530a.png)

The third error message is this one that you had before the fix. It does not show up anymore, but possibly could once the Client register program is made like the UI of the MCH program.
![image](https://user-images.githubusercontent.com/36447512/44339753-d9b4ab00-a482-11e8-9c1b-35d054d049cc.png)

**Comment by AkubaD** [comment]
Hi @lukasewvd 
Do you have any update on this and on incorporating Monjur's solution for #106 ?
